version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: h2eaux-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: h2eaux_gestion
    volumes:
      - mongodb_data:/data/db
      - ./deployment/scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - h2eaux-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: h2eaux-backend
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - DB_NAME=h2eaux_gestion
      - JWT_SECRET=dev-secret-key-not-for-production
      - ENVIRONMENT=development
      - ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
    working_dir: /app
    command: uvicorn server:app --host 0.0.0.0 --port 8001 --reload
    networks:
      - h2eaux-network

  frontend:
    image: nginx:alpine
    container_name: h2eaux-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./deployment/nginx/nginx-docker.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    networks:
      - h2eaux-network

volumes:
  mongodb_data:
    driver: local

networks:
  h2eaux-network:
    driver: bridge